---
# Server configuration
server:
    listen: 8080
    workers: 4
    upstream:
        - id: jsonplaceholder
          url: jsonplaceholder.typicode.com

        - id: dummyjson
          url: dummyjson.com

    headers:
        - key: x-forward-for
          value: $ip
        - key: Authorization
          value: Bearer xyz
    rules:
        - path: /test
          upstrams: [dummyjson]

        - path: /
          upstrams: [jsonplaceholder]
