---
# Server configuration
server:
  listen: 8080
  workers: 4
  upstream:
    - id: node1
      url: jsonplaceholder.typicode.com
    - id: node2
      url: http://localhost:8002
  headers:
    - key: x-forward-for
      value: $ip
    - key: Authorization
      value: Bearer xyz
  rules:
    - path: /
      upstrams: [node1, node2]
    - path: /admin
      upstrams: [node2]
    - path: /todos
      upstrams: [node1]
